# Generated by Django 5.2.5 on 2025-08-17 19:37

import accounts.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_autheruser_revieweruser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AutherUser',
        ),
        migrations.CreateModel(
            name='AuthorUser',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', accounts.managers.AuthorUserManager()),
            ],
        ),
    ]
